### Q1. Write a program to distinguish between Array Indexing and Fancy Indexing.

In [7]:
import numpy as np 

arr = np.array([1,2,3,4,5,6])

# Array Indexing
print("Array Indexing : ")
print("Array[0] : ", arr[0])
print("Array[2] : ", arr[2])
print("Array[5] : ", arr[5])

print()
# Fancy Indexing
print("Array Indexing : ")
print("Array[0], Array[2], Array[5] : ", arr[[0, 2, 5]])

Array Indexing : 
Array[0] :  1
Array[2] :  3
Array[5] :  6

Array Indexing : 
Array[0], Array[2], Array[5] :  [1 3 6]


### Q2. Execute the 2D array Slicing.

In [26]:
import numpy as np 

arr = np.array([
    [1,2,3,5,1,1],
    [4,5,6,5,6,7],
    [7,8,9,2,4,8]
])

print("Array : ", arr[0:2,2:5])

Array :  [[3 5 1]
 [6 5 6]]


### Q3. Create the 5-Dimensional arrays using ‘ndmin’.

In [24]:
import numpy as np

arr = np.array([1,2,3], ndmin= 5)

print("Array: ", arr)
print("Dimension of the array", arr.ndim)

Array:  [[[[[1 2 3]]]]]
Dimension of the array 5


### Q4. Reshape the array from 1-D to 2-D array.

In [30]:
import numpy as np 

arr = np.array([1,2,3,4,5,6,7,8,9])

arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Q5. Perform the Stack functions in Numpy arrays – Stack(), hstack(), vstack(), and dstack().

In [47]:
import numpy as np

arr1 = np.array([
    [1,2,3],
    [4,5,6]
    ])

arr2 = np.array([
    [7,8,9],
    [4,5,6]
])

print("Stack : ", np.stack((arr1, arr2)))
print()
print("Horizontal Stack : ", np.hstack((arr1,arr2)))
print()
print("Vertical Stack :", np.vstack((arr1,arr2)))
print()
print("DStack :", np.dstack((arr1,arr2)))

Stack :  [[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [4 5 6]]]

Horizontal Stack :  [[1 2 3 7 8 9]
 [4 5 6 4 5 6]]

Vertical Stack : [[1 2 3]
 [4 5 6]
 [7 8 9]
 [4 5 6]]

DStack : [[[1 7]
  [2 8]
  [3 9]]

 [[4 4]
  [5 5]
  [6 6]]]


### Q6. Perform the searchsort method in Numpy array.

##### numpy.searchsorted(a, v, side='left', sorter=None)
Find indices where elements should be inserted to maintain order.

Find the indices into a sorted array a such that, if the corresponding elements in v were inserted before the indices, the order of a would be preserved.

In [58]:
import numpy as np

arr = np.array([1,2,3,4,8,9,10])
new = np.array([5,11])
print(np.searchsorted(arr, new))

[4 7]


#### Q7. Create Numpy Structured array using your domain features.

In [103]:
import numpy as np

# Tickets sold for the events 
tickets = np.array([
    ('Morning', 200, 'Afternoon', 300, 'Evening', 490),
    ('Morning', 400, 'Afternoon', 600, 'Evening', 900),
    ('Morning', 200, 'Afternoon', 370, 'Evening', 700)
])

for i in range(len(tickets)):
    print(f"Tickets sold on day {i+1} : {tickets[i]}")
    print(f"\t Tickets sold for Morning Event : {tickets[i][1]}")
    print(f"\t Tickets sold for Afternoon Event : {tickets[i][3]}")
    print(f"\t Tickets sold for Evening Event : {tickets[i][5]}")
    print()



Tickets sold on day 1 : ['Morning' '200' 'Afternoon' '300' 'Evening' '490']
	 Tickets sold for Morning Event : 200
	 Tickets sold for Afternoon Event : 300
	 Tickets sold for Evening Event : 490

Tickets sold on day 2 : ['Morning' '400' 'Afternoon' '600' 'Evening' '900']
	 Tickets sold for Morning Event : 400
	 Tickets sold for Afternoon Event : 600
	 Tickets sold for Evening Event : 900

Tickets sold on day 3 : ['Morning' '200' 'Afternoon' '370' 'Evening' '700']
	 Tickets sold for Morning Event : 200
	 Tickets sold for Afternoon Event : 370
	 Tickets sold for Evening Event : 700



### Q8. Create Data frame using List and Dictionary.

In [93]:
import pandas as pd
df = pd.read_csv("./event_management_dataset.csv")

print("Using Lists :")
print("Attendees for the 1st 10 Events : ", list(df["Attendees"][:10]))
print("Registration Fee for the 1st 10 Events : ", list(df["Registration Fee"][:10]))

print()
print("Using Dictionary")
for event in df:
    dict ={
        "Event Name" : df["Event Name"][0],
        "Organizer": df["Organizer"][0]
    }
    print(dict)

Using Lists :
Attendees for the 1st 10 Events :  [911, 985, 741, 968, 387, 304, 539, 659, 966, 869]
Registration Fee for the 1st 10 Events :  [36, 81, 55, 92, 88, 90, 60, 41, 57, 60]

Using Dictionary
{'Event Name': 'Vision-oriented 6thgeneration task-force', 'Organizer': 'Rivera LLC'}
{'Event Name': 'Vision-oriented 6thgeneration task-force', 'Organizer': 'Rivera LLC'}
{'Event Name': 'Vision-oriented 6thgeneration task-force', 'Organizer': 'Rivera LLC'}
{'Event Name': 'Vision-oriented 6thgeneration task-force', 'Organizer': 'Rivera LLC'}
{'Event Name': 'Vision-oriented 6thgeneration task-force', 'Organizer': 'Rivera LLC'}
{'Event Name': 'Vision-oriented 6thgeneration task-force', 'Organizer': 'Rivera LLC'}
{'Event Name': 'Vision-oriented 6thgeneration task-force', 'Organizer': 'Rivera LLC'}
{'Event Name': 'Vision-oriented 6thgeneration task-force', 'Organizer': 'Rivera LLC'}
{'Event Name': 'Vision-oriented 6thgeneration task-force', 'Organizer': 'Rivera LLC'}
{'Event Name': 'Vision-or

### Q9. Create Data frame on your Domain area and perform the following operations to find and eliminate the missing data from the dataset.
• isnull()
• notnull()
• dropna()
• fillna()
• replace()
• interpolate()

In [5]:
import pandas as pd
import numpy as np


df = pd.read_csv("./event_management_dataset.csv")

# Display the DataFrame
print("Original DataFrame:")
print(df)

# Check for missing data using isnull()
print("\nChecking for missing data using isnull():")
print(df.isnull())

# Check for non-missing data using notnull()
print("\nChecking for non-missing data using notnull():")
print(df.notnull())

# Drop rows with missing data using dropna()
print("\nDropping rows with missing data using dropna():")
df_dropna = df.dropna()
print(df_dropna)

# Fill missing data using fillna()
print("\nFilling missing data using fillna():")
df_fillna = df.fillna(0)  # Filling missing data with 0 (you can use other values as well)
print(df_fillna)

# Replace missing data using replace()
print("\nReplacing missing data using replace():")
df_replace = df.replace(np.nan, -1)  # Replace NaN with -1 (you can use other values as well)
print(df_replace)

# Interpolate missing data using interpolate()
print("\nInterpolating missing data using interpolate():")
df_interpolate = df.interpolate()
print(df_interpolate)


Original DataFrame:
    Event ID                                   Event Name        Date  \
0      E0001    Future-proofed incremental implementation  2023-08-29   
1      E0002    Front-line bandwidth-monitored monitoring  2023-10-08   
2      E0003               Ergonomic systematic challenge  2023-08-20   
3      E0004                 Fundamental logistical array  2023-10-16   
4      E0005            Distributed stable superstructure  2023-08-19   
..       ...                                          ...         ...   
245    E0246                User-centric scalable success  2023-08-26   
246    E0247  Assimilated 6thgeneration pricing structure  2023-09-03   
247    E0248                  Synergized explicit archive  2023-09-11   
248    E0249              Integrated multi-state intranet  2023-10-03   
249    E0250    Vision-oriented zero tolerance throughput  2023-09-18   

               Location                   Organizer  Attendees  \
0           Normanhaven  Johnson, Mil

C:\Users\ASUS\AppData\Local\Temp\ipykernel_13984\2543753243.py:36: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df_interpolate = df.interpolate()


### Q10. Perform the Hierarchical Indexing in the above created dataset.

In [6]:
import pandas as pd
import numpy as np

df = pd.read_csv("./event_management_dataset.csv")

# Set hierarchical indexing
df.set_index(['Date', 'Event Name'], inplace=True)

# # Display the DataFrame with hierarchical indexing
print("DataFrame with Hierarchical Indexing:")
print(df)


DataFrame with Hierarchical Indexing:
                                                       Event ID  \
Date       Event Name                                             
2023-08-29 Future-proofed incremental implementation      E0001   
2023-10-08 Front-line bandwidth-monitored monitoring      E0002   
2023-08-20 Ergonomic systematic challenge                 E0003   
2023-10-16 Fundamental logistical array                   E0004   
2023-08-19 Distributed stable superstructure              E0005   
...                                                         ...   
2023-08-26 User-centric scalable success                  E0246   
2023-09-03 Assimilated 6thgeneration pricing structure    E0247   
2023-09-11 Synergized explicit archive                    E0248   
2023-10-03 Integrated multi-state intranet                E0249   
2023-09-18 Vision-oriented zero tolerance throughput      E0250   

                                                                  Location  \
Date       E